//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios_Requerimientos
    {
        public int Codigo_Requerimientos { get; set; }
        public string Comentario { get; set; }
    
        public virtual Solicitud_Requerimientos Solicitud_Requerimientos { get; set; }
    }
}
