//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBProyectoSkyNetEntities : DbContext
    {
        public DBProyectoSkyNetEntities()
            : base("name=DBProyectoSkyNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comentarios_Incidencias> Comentarios_Incidencias { get; set; }
        public virtual DbSet<Comentarios_Requerimientos> Comentarios_Requerimientos { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<Departamento_Tecnico> Departamento_Tecnico { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Receptor_Solicitudes> Receptor_Solicitudes { get; set; }
        public virtual DbSet<Solicitud_Requerimientos> Solicitud_Requerimientos { get; set; }
        public virtual DbSet<Tecnico_Soporte> Tecnico_Soporte { get; set; }
        public virtual DbSet<Telefonos_Clientes> Telefonos_Clientes { get; set; }
        public virtual DbSet<Telefonos_Tecnicos> Telefonos_Tecnicos { get; set; }
        public virtual DbSet<Vista_por_DeptoTecnico> Vista_por_DeptoTecnico { get; set; }
        public virtual DbSet<Vista_por_Estado> Vista_por_Estado { get; set; }
        public virtual DbSet<Vista_por_Fecha> Vista_por_Fecha { get; set; }
        public virtual DbSet<Vista_por_Solicitante> Vista_por_Solicitante { get; set; }
        public virtual DbSet<Vista_por_Tecnico> Vista_por_Tecnico { get; set; }
        public virtual DbSet<database_firewall_rules1> database_firewall_rules1 { get; set; }
    
        public virtual int sp_actualizar_cliente(Nullable<int> id, string prim_Nombre, string seg_Nombre, string prim_Apellido, string seg_Apellido, string str_direccion, string st_corr)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var prim_NombreParameter = prim_Nombre != null ?
                new ObjectParameter("Prim_Nombre", prim_Nombre) :
                new ObjectParameter("Prim_Nombre", typeof(string));
    
            var seg_NombreParameter = seg_Nombre != null ?
                new ObjectParameter("Seg_Nombre", seg_Nombre) :
                new ObjectParameter("Seg_Nombre", typeof(string));
    
            var prim_ApellidoParameter = prim_Apellido != null ?
                new ObjectParameter("Prim_Apellido", prim_Apellido) :
                new ObjectParameter("Prim_Apellido", typeof(string));
    
            var seg_ApellidoParameter = seg_Apellido != null ?
                new ObjectParameter("Seg_Apellido", seg_Apellido) :
                new ObjectParameter("Seg_Apellido", typeof(string));
    
            var str_direccionParameter = str_direccion != null ?
                new ObjectParameter("str_direccion", str_direccion) :
                new ObjectParameter("str_direccion", typeof(string));
    
            var st_corrParameter = st_corr != null ?
                new ObjectParameter("st_corr", st_corr) :
                new ObjectParameter("st_corr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_cliente", idParameter, prim_NombreParameter, seg_NombreParameter, prim_ApellidoParameter, seg_ApellidoParameter, str_direccionParameter, st_corrParameter);
        }
    
        public virtual int sp_actualizar_deptoTecnico(Nullable<int> id, string nomb, string direc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombParameter = nomb != null ?
                new ObjectParameter("Nomb", nomb) :
                new ObjectParameter("Nomb", typeof(string));
    
            var direcParameter = direc != null ?
                new ObjectParameter("direc", direc) :
                new ObjectParameter("direc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_deptoTecnico", idParameter, nombParameter, direcParameter);
        }
    
        public virtual int sp_actualizar_Estado(Nullable<int> id, string desc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_Estado", idParameter, descParameter);
        }
    
        public virtual int sp_actualizar_incidencia(Nullable<int> id, Nullable<int> codres, Nullable<int> codsol, string titulo, string desc, string adj, Nullable<int> cod_tec, Nullable<System.DateTime> fech, Nullable<int> est)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codresParameter = codres.HasValue ?
                new ObjectParameter("codres", codres) :
                new ObjectParameter("codres", typeof(int));
    
            var codsolParameter = codsol.HasValue ?
                new ObjectParameter("codsol", codsol) :
                new ObjectParameter("codsol", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var cod_tecParameter = cod_tec.HasValue ?
                new ObjectParameter("cod_tec", cod_tec) :
                new ObjectParameter("cod_tec", typeof(int));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var estParameter = est.HasValue ?
                new ObjectParameter("est", est) :
                new ObjectParameter("est", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_incidencia", idParameter, codresParameter, codsolParameter, tituloParameter, descParameter, adjParameter, cod_tecParameter, fechParameter, estParameter);
        }
    
        public virtual int sp_actualizar_Perfil(Nullable<int> id, string descpr)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descprParameter = descpr != null ?
                new ObjectParameter("descpr", descpr) :
                new ObjectParameter("descpr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_Perfil", idParameter, descprParameter);
        }
    
        public virtual int sp_actualizar_receptor(Nullable<int> id, string prim_Nombre, string seg_Nombre, string prim_Apellido, string seg_Apellido, string str_direccion, Nullable<System.DateTime> fech, string corr, string dp, Nullable<int> codper, string pas)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var prim_NombreParameter = prim_Nombre != null ?
                new ObjectParameter("Prim_Nombre", prim_Nombre) :
                new ObjectParameter("Prim_Nombre", typeof(string));
    
            var seg_NombreParameter = seg_Nombre != null ?
                new ObjectParameter("Seg_Nombre", seg_Nombre) :
                new ObjectParameter("Seg_Nombre", typeof(string));
    
            var prim_ApellidoParameter = prim_Apellido != null ?
                new ObjectParameter("Prim_Apellido", prim_Apellido) :
                new ObjectParameter("Prim_Apellido", typeof(string));
    
            var seg_ApellidoParameter = seg_Apellido != null ?
                new ObjectParameter("Seg_Apellido", seg_Apellido) :
                new ObjectParameter("Seg_Apellido", typeof(string));
    
            var str_direccionParameter = str_direccion != null ?
                new ObjectParameter("str_direccion", str_direccion) :
                new ObjectParameter("str_direccion", typeof(string));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var corrParameter = corr != null ?
                new ObjectParameter("corr", corr) :
                new ObjectParameter("corr", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var codperParameter = codper.HasValue ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(int));
    
            var pasParameter = pas != null ?
                new ObjectParameter("pas", pas) :
                new ObjectParameter("pas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_receptor", idParameter, prim_NombreParameter, seg_NombreParameter, prim_ApellidoParameter, seg_ApellidoParameter, str_direccionParameter, fechParameter, corrParameter, dpParameter, codperParameter, pasParameter);
        }
    
        public virtual int sp_actualizar_solicitud_requimientos(Nullable<int> id, Nullable<int> codrecep, Nullable<int> codsol, string titulo, string desc, string adj, Nullable<int> cod_tec, Nullable<System.DateTime> fech, Nullable<int> est)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codrecepParameter = codrecep.HasValue ?
                new ObjectParameter("codrecep", codrecep) :
                new ObjectParameter("codrecep", typeof(int));
    
            var codsolParameter = codsol.HasValue ?
                new ObjectParameter("codsol", codsol) :
                new ObjectParameter("codsol", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var cod_tecParameter = cod_tec.HasValue ?
                new ObjectParameter("cod_tec", cod_tec) :
                new ObjectParameter("cod_tec", typeof(int));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var estParameter = est.HasValue ?
                new ObjectParameter("est", est) :
                new ObjectParameter("est", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_solicitud_requimientos", idParameter, codrecepParameter, codsolParameter, tituloParameter, descParameter, adjParameter, cod_tecParameter, fechParameter, estParameter);
        }
    
        public virtual int sp_actualizar_tecnico(Nullable<int> id, string prim_Nombre, string seg_Nombre, string prim_Apellido, string seg_Apellido, string str_direccion, Nullable<System.DateTime> fecha_nac, string corr, string dp, Nullable<int> coddepa, Nullable<int> codperf, string pas)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var prim_NombreParameter = prim_Nombre != null ?
                new ObjectParameter("Prim_Nombre", prim_Nombre) :
                new ObjectParameter("Prim_Nombre", typeof(string));
    
            var seg_NombreParameter = seg_Nombre != null ?
                new ObjectParameter("Seg_Nombre", seg_Nombre) :
                new ObjectParameter("Seg_Nombre", typeof(string));
    
            var prim_ApellidoParameter = prim_Apellido != null ?
                new ObjectParameter("Prim_Apellido", prim_Apellido) :
                new ObjectParameter("Prim_Apellido", typeof(string));
    
            var seg_ApellidoParameter = seg_Apellido != null ?
                new ObjectParameter("Seg_Apellido", seg_Apellido) :
                new ObjectParameter("Seg_Apellido", typeof(string));
    
            var str_direccionParameter = str_direccion != null ?
                new ObjectParameter("str_direccion", str_direccion) :
                new ObjectParameter("str_direccion", typeof(string));
    
            var fecha_nacParameter = fecha_nac.HasValue ?
                new ObjectParameter("fecha_nac", fecha_nac) :
                new ObjectParameter("fecha_nac", typeof(System.DateTime));
    
            var corrParameter = corr != null ?
                new ObjectParameter("corr", corr) :
                new ObjectParameter("corr", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var coddepaParameter = coddepa.HasValue ?
                new ObjectParameter("coddepa", coddepa) :
                new ObjectParameter("coddepa", typeof(int));
    
            var codperfParameter = codperf.HasValue ?
                new ObjectParameter("codperf", codperf) :
                new ObjectParameter("codperf", typeof(int));
    
            var pasParameter = pas != null ?
                new ObjectParameter("pas", pas) :
                new ObjectParameter("pas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_tecnico", idParameter, prim_NombreParameter, seg_NombreParameter, prim_ApellidoParameter, seg_ApellidoParameter, str_direccionParameter, fecha_nacParameter, corrParameter, dpParameter, coddepaParameter, codperfParameter, pasParameter);
        }
    
        public virtual int sp_actualizar_telCliente(Nullable<int> id, string numtel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var numtelParameter = numtel != null ?
                new ObjectParameter("numtel", numtel) :
                new ObjectParameter("numtel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_telCliente", idParameter, numtelParameter);
        }
    
        public virtual int sp_actualizar_telTecnico(Nullable<int> id, string numtel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var numtelParameter = numtel != null ?
                new ObjectParameter("numtel", numtel) :
                new ObjectParameter("numtel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_actualizar_telTecnico", idParameter, numtelParameter);
        }
    
        public virtual int sp_insert_clienteID(string primnomb, string segnomb, string primapellido, string segapellido, string direcc, string corr)
        {
            var primnombParameter = primnomb != null ?
                new ObjectParameter("primnomb", primnomb) :
                new ObjectParameter("primnomb", typeof(string));
    
            var segnombParameter = segnomb != null ?
                new ObjectParameter("segnomb", segnomb) :
                new ObjectParameter("segnomb", typeof(string));
    
            var primapellidoParameter = primapellido != null ?
                new ObjectParameter("primapellido", primapellido) :
                new ObjectParameter("primapellido", typeof(string));
    
            var segapellidoParameter = segapellido != null ?
                new ObjectParameter("segapellido", segapellido) :
                new ObjectParameter("segapellido", typeof(string));
    
            var direccParameter = direcc != null ?
                new ObjectParameter("direcc", direcc) :
                new ObjectParameter("direcc", typeof(string));
    
            var corrParameter = corr != null ?
                new ObjectParameter("corr", corr) :
                new ObjectParameter("corr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_clienteID", primnombParameter, segnombParameter, primapellidoParameter, segapellidoParameter, direccParameter, corrParameter);
        }
    
        public virtual int sp_insert_Comentario_incidencia(Nullable<int> cod, string com)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var comParameter = com != null ?
                new ObjectParameter("com", com) :
                new ObjectParameter("com", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_Comentario_incidencia", codParameter, comParameter);
        }
    
        public virtual int sp_insert_Comentario_solicitud(Nullable<int> cod, string com)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var comParameter = com != null ?
                new ObjectParameter("com", com) :
                new ObjectParameter("com", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_Comentario_solicitud", codParameter, comParameter);
        }
    
        public virtual int sp_insert_DeptoTecnico(string nomb, string direcc)
        {
            var nombParameter = nomb != null ?
                new ObjectParameter("nomb", nomb) :
                new ObjectParameter("nomb", typeof(string));
    
            var direccParameter = direcc != null ?
                new ObjectParameter("direcc", direcc) :
                new ObjectParameter("direcc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_DeptoTecnico", nombParameter, direccParameter);
        }
    
        public virtual int sp_insert_estados(string descest)
        {
            var descestParameter = descest != null ?
                new ObjectParameter("descest", descest) :
                new ObjectParameter("descest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_estados", descestParameter);
        }
    
        public virtual int sp_insert_incidencia(Nullable<int> codrecept, Nullable<int> codsol, string tit, string desc, string adj, Nullable<int> codtec, Nullable<System.DateTime> fecha, Nullable<int> est)
        {
            var codreceptParameter = codrecept.HasValue ?
                new ObjectParameter("codrecept", codrecept) :
                new ObjectParameter("codrecept", typeof(int));
    
            var codsolParameter = codsol.HasValue ?
                new ObjectParameter("codsol", codsol) :
                new ObjectParameter("codsol", typeof(int));
    
            var titParameter = tit != null ?
                new ObjectParameter("tit", tit) :
                new ObjectParameter("tit", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var codtecParameter = codtec.HasValue ?
                new ObjectParameter("codtec", codtec) :
                new ObjectParameter("codtec", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estParameter = est.HasValue ?
                new ObjectParameter("est", est) :
                new ObjectParameter("est", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_incidencia", codreceptParameter, codsolParameter, titParameter, descParameter, adjParameter, codtecParameter, fechaParameter, estParameter);
        }
    
        public virtual int sp_insert_perfil(string perf)
        {
            var perfParameter = perf != null ?
                new ObjectParameter("perf", perf) :
                new ObjectParameter("perf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_perfil", perfParameter);
        }
    
        public virtual int sp_insert_receptor(string primnomb, string segnomb, string primapellido, string segapellido, string direcc, Nullable<System.DateTime> fech, string corr, string dp, Nullable<int> codper, string pas)
        {
            var primnombParameter = primnomb != null ?
                new ObjectParameter("primnomb", primnomb) :
                new ObjectParameter("primnomb", typeof(string));
    
            var segnombParameter = segnomb != null ?
                new ObjectParameter("segnomb", segnomb) :
                new ObjectParameter("segnomb", typeof(string));
    
            var primapellidoParameter = primapellido != null ?
                new ObjectParameter("primapellido", primapellido) :
                new ObjectParameter("primapellido", typeof(string));
    
            var segapellidoParameter = segapellido != null ?
                new ObjectParameter("segapellido", segapellido) :
                new ObjectParameter("segapellido", typeof(string));
    
            var direccParameter = direcc != null ?
                new ObjectParameter("direcc", direcc) :
                new ObjectParameter("direcc", typeof(string));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var corrParameter = corr != null ?
                new ObjectParameter("corr", corr) :
                new ObjectParameter("corr", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var codperParameter = codper.HasValue ?
                new ObjectParameter("codper", codper) :
                new ObjectParameter("codper", typeof(int));
    
            var pasParameter = pas != null ?
                new ObjectParameter("pas", pas) :
                new ObjectParameter("pas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_receptor", primnombParameter, segnombParameter, primapellidoParameter, segapellidoParameter, direccParameter, fechParameter, corrParameter, dpParameter, codperParameter, pasParameter);
        }
    
        public virtual int sp_insert_solicitudRequerimientos(Nullable<int> codrep, Nullable<int> codsol, string titl, string desc, string adj, Nullable<int> codtec, Nullable<System.DateTime> fech, Nullable<int> est)
        {
            var codrepParameter = codrep.HasValue ?
                new ObjectParameter("codrep", codrep) :
                new ObjectParameter("codrep", typeof(int));
    
            var codsolParameter = codsol.HasValue ?
                new ObjectParameter("codsol", codsol) :
                new ObjectParameter("codsol", typeof(int));
    
            var titlParameter = titl != null ?
                new ObjectParameter("titl", titl) :
                new ObjectParameter("titl", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var codtecParameter = codtec.HasValue ?
                new ObjectParameter("codtec", codtec) :
                new ObjectParameter("codtec", typeof(int));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var estParameter = est.HasValue ?
                new ObjectParameter("est", est) :
                new ObjectParameter("est", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_solicitudRequerimientos", codrepParameter, codsolParameter, titlParameter, descParameter, adjParameter, codtecParameter, fechParameter, estParameter);
        }
    
        public virtual int sp_insert_tecnico(string primnomb, string segnomb, string primapellido, string segapellido, string direcc, Nullable<System.DateTime> fech, string corr, string dp, Nullable<int> coddepa, Nullable<int> codperf, string pas)
        {
            var primnombParameter = primnomb != null ?
                new ObjectParameter("primnomb", primnomb) :
                new ObjectParameter("primnomb", typeof(string));
    
            var segnombParameter = segnomb != null ?
                new ObjectParameter("segnomb", segnomb) :
                new ObjectParameter("segnomb", typeof(string));
    
            var primapellidoParameter = primapellido != null ?
                new ObjectParameter("primapellido", primapellido) :
                new ObjectParameter("primapellido", typeof(string));
    
            var segapellidoParameter = segapellido != null ?
                new ObjectParameter("segapellido", segapellido) :
                new ObjectParameter("segapellido", typeof(string));
    
            var direccParameter = direcc != null ?
                new ObjectParameter("direcc", direcc) :
                new ObjectParameter("direcc", typeof(string));
    
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var corrParameter = corr != null ?
                new ObjectParameter("corr", corr) :
                new ObjectParameter("corr", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var coddepaParameter = coddepa.HasValue ?
                new ObjectParameter("coddepa", coddepa) :
                new ObjectParameter("coddepa", typeof(int));
    
            var codperfParameter = codperf.HasValue ?
                new ObjectParameter("codperf", codperf) :
                new ObjectParameter("codperf", typeof(int));
    
            var pasParameter = pas != null ?
                new ObjectParameter("pas", pas) :
                new ObjectParameter("pas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_tecnico", primnombParameter, segnombParameter, primapellidoParameter, segapellidoParameter, direccParameter, fechParameter, corrParameter, dpParameter, coddepaParameter, codperfParameter, pasParameter);
        }
    
        public virtual int sp_insert_TelCliente(Nullable<int> cod, string tel)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_TelCliente", codParameter, telParameter);
        }
    
        public virtual int sp_insert_Teltecnico(Nullable<int> cod, string tel)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_Teltecnico", codParameter, telParameter);
        }
    
        public virtual ObjectResult<sp_ver_clientesID_Result> sp_ver_clientesID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_clientesID_Result>("sp_ver_clientesID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_deptotecnicoID_Result> sp_ver_deptotecnicoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_deptotecnicoID_Result>("sp_ver_deptotecnicoID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_estados_Result> sp_ver_estados(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_estados_Result>("sp_ver_estados", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_incidenciasID_Result> sp_ver_incidenciasID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_incidenciasID_Result>("sp_ver_incidenciasID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_perfiles_Result> sp_ver_perfiles(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_perfiles_Result>("sp_ver_perfiles", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_por_DeptoTecnico_Result> sp_ver_por_DeptoTecnico(string depa, string usu)
        {
            var depaParameter = depa != null ?
                new ObjectParameter("depa", depa) :
                new ObjectParameter("depa", typeof(string));
    
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_por_DeptoTecnico_Result>("sp_ver_por_DeptoTecnico", depaParameter, usuParameter);
        }
    
        public virtual ObjectResult<sp_ver_por_estado_Result> sp_ver_por_estado(string est, string usu)
        {
            var estParameter = est != null ?
                new ObjectParameter("est", est) :
                new ObjectParameter("est", typeof(string));
    
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_por_estado_Result>("sp_ver_por_estado", estParameter, usuParameter);
        }
    
        public virtual ObjectResult<sp_ver_por_fecha_Result> sp_ver_por_fecha(Nullable<System.DateTime> fech, string usu)
        {
            var fechParameter = fech.HasValue ?
                new ObjectParameter("fech", fech) :
                new ObjectParameter("fech", typeof(System.DateTime));
    
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_por_fecha_Result>("sp_ver_por_fecha", fechParameter, usuParameter);
        }
    
        public virtual ObjectResult<sp_ver_por_solicitante_Result> sp_ver_por_solicitante(string nomb, string ape, string usu)
        {
            var nombParameter = nomb != null ?
                new ObjectParameter("nomb", nomb) :
                new ObjectParameter("nomb", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_por_solicitante_Result>("sp_ver_por_solicitante", nombParameter, apeParameter, usuParameter);
        }
    
        public virtual ObjectResult<sp_ver_por_tecnico_Result> sp_ver_por_tecnico(string nomb, string ape, string usu)
        {
            var nombParameter = nomb != null ?
                new ObjectParameter("nomb", nomb) :
                new ObjectParameter("nomb", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var usuParameter = usu != null ?
                new ObjectParameter("usu", usu) :
                new ObjectParameter("usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_por_tecnico_Result>("sp_ver_por_tecnico", nombParameter, apeParameter, usuParameter);
        }
    
        public virtual ObjectResult<sp_ver_receptorID_Result> sp_ver_receptorID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_receptorID_Result>("sp_ver_receptorID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_solicitudRequerimientosID_Result> sp_ver_solicitudRequerimientosID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_solicitudRequerimientosID_Result>("sp_ver_solicitudRequerimientosID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_tecnicoID_Result> sp_ver_tecnicoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_tecnicoID_Result>("sp_ver_tecnicoID", idParameter);
        }
    
        public virtual ObjectResult<sp_ver_todosclientes_Result> sp_ver_todosclientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosclientes_Result>("sp_ver_todosclientes");
        }
    
        public virtual ObjectResult<sp_ver_todosdeptotecnico_Result> sp_ver_todosdeptotecnico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosdeptotecnico_Result>("sp_ver_todosdeptotecnico");
        }
    
        public virtual ObjectResult<sp_ver_todosestados_Result> sp_ver_todosestados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosestados_Result>("sp_ver_todosestados");
        }
    
        public virtual ObjectResult<sp_ver_todosincidencias_Result> sp_ver_todosincidencias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosincidencias_Result>("sp_ver_todosincidencias");
        }
    
        public virtual ObjectResult<sp_ver_todosperfiles_Result> sp_ver_todosperfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosperfiles_Result>("sp_ver_todosperfiles");
        }
    
        public virtual ObjectResult<sp_ver_todosreceptor_Result> sp_ver_todosreceptor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todosreceptor_Result>("sp_ver_todosreceptor");
        }
    
        public virtual ObjectResult<sp_ver_todossolicitudRequerimientos_Result> sp_ver_todossolicitudRequerimientos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todossolicitudRequerimientos_Result>("sp_ver_todossolicitudRequerimientos");
        }
    
        public virtual ObjectResult<sp_ver_todoTecnicos_Result> sp_ver_todoTecnicos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_todoTecnicos_Result>("sp_ver_todoTecnicos");
        }
    }
}
